# Generated by Django 6.0.7 on 2026-07-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_badge_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goal',
            field=models.CharField(blank=True, choices=[('learn', 'Learn programming'), ('job', 'Get a developer job'), ('ai', 'Build AI tools'), ('automate', 'Automate tasks'), ('web', 'Create websites'), ('apps', 'Build apps')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='programming_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Complete beginner'), ('basic', 'Basic programming knowledge'), ('intermediate', 'Intermediate developer'), ('advanced', 'Professional developer')], max_length=20, null=True),
        ),
    ]
