# Generated by Django 6.0.7 on 2026-07-18 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepDiveLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Level number')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtitle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(default='📘', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Deep-Dive Level',
                'verbose_name_plural': 'Deep-Dive Levels',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DeepDiveSubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Sub-section number')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_exam', models.BooleanField(default=False, verbose_name='Is exam')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Is premium')),
                ('order', models.PositiveIntegerField(default=0)),
                ('theory', models.TextField(blank=True, verbose_name='Theory (HTML)')),
                ('mcqs', models.JSONField(blank=True, default=list, verbose_name='MCQs')),
                ('fill_blanks', models.JSONField(blank=True, default=list, verbose_name='Fill-in-the-blank')),
                ('writing_exercises', models.JSONField(blank=True, default=list, verbose_name='Writing exercises')),
                ('golden_key_threshold', models.PositiveIntegerField(default=100, verbose_name='IQ points for golden key')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='deepdive.deepdivelevel')),
            ],
            options={
                'verbose_name': 'Deep-Dive Sub-Section',
                'verbose_name_plural': 'Deep-Dive Sub-Sections',
                'ordering': ['level__number', 'number'],
                'unique_together': {('level', 'number')},
            },
        ),
        migrations.CreateModel(
            name='IQPointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('transaction_type', models.CharField(choices=[('earned', 'Earned'), ('spent', 'Spent')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subsection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deepdive.deepdivesubsection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iq_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IQ Point Transaction',
                'verbose_name_plural': 'IQ Point Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('has_golden_key', models.BooleanField(default=False)),
                ('iq_points_total', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='deepdive.deepdivelevel')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'unique_together': {('user', 'level')},
            },
        ),
        migrations.CreateModel(
            name='GoldenKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('iq_points_earned', models.PositiveIntegerField(default=0)),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golden_keys', to='deepdive.deepdivesubsection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golden_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Golden Key',
                'verbose_name_plural': 'Golden Keys',
                'unique_together': {('user', 'subsection')},
            },
        ),
    ]
